name: bytetranslateflutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.2.0 <4.0.0"

dependencies:
    audioplayers: ^5.2.1
    curved_labeled_navigation_bar: ^2.0.2
    flutter:
        sdk: flutter
    path_provider: ^2.1.1
    permission_handler: ^11.1.0
    provider: ^6.0.0
    record: ^5.0.1
    whisper_flutter_plus: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1

flutter:
    uses-material-design: true
